### ISSUE TITLE
Password in test and test2

### ISSUE THREAD

**Issue by jasondilworth56** [Fuzzwah/ir_webstats_rc#1]
Hi Rob,

Just looking through the improvements you've made to this package after working on a fix myself today. Noticed that in your test and test2 files you've got a password. I wouldn't try it, and assume it's old anyway, but thought I'd give you the heads up.

Cheers,
Jason

**Comment by Fuzzwah** [comment]
Thanks. It was indeed an old password. I've cleaned the repo and switched my test files to use env vars.
